POST http://localhost:3004/user
content-type: application/json

{
    "name": "testing",
    "email": "test@alpha.com",
    "password": "omg"
}

###

GET http://localhost:3004/user

###

GET http://localhost:3004/user/edf5ac05-8aa7-4ecc-8158-fd1e3bddd308