POST http://localhost:3002/product
content-type: application/json

{
    "userId": "edf5ac05-8aa7-4ecc-8158-fd1e3bddd308",
    "name": "product01",
    "price": 45,
    "quantity": 1
}

###

POST http://localhost:3002/product/canbuy
content-type: application/json

{
    "productId": "29dcd2ff-b714-4b41-90b2-b392d700817c",
    "payed": 45
}

###

POST http://localhost:3002/product/canbuy
content-type: application/json

{
    "productId": "29dcd2ff-b714-4b41-90b2-b392d700817c",
    "payed": 1
}

###

POST http://localhost:3002/product/bought
content-type: application/json

{
    "productId": "29dcd2ff-b714-4b41-90b2-b392d700817c"
}

###

GET http://localhost:3002/product

###

GET http://localhost:3002/product/0c17d96a-4125-489a-b35b-8e96ee4931e9